import { FiDownload } from "react-icons/fi";
import ScoreDial from "../ui/ScoreDial";
import StatusPill from "../ui/StatusPill";
import Button from "../ui/Button";
import ReportSection from "./ReportSection";
import { CompetencyBars, BulletList } from "./ReportBits";
import { formatDate } from "../../utils/formatters";

const RESULT_TONE = { "Strong Match": "green", "Potential Match": "amber", "Keep Practicing": "teal" };

const CandidateReportView = ({ data, onDownloadPdf, downloading }) => {
  const { jobDescription, generatedAt, score, report } = data;

  return (
    <div className="rounded-2xl border border-line bg-white p-6 sm:p-8">
      <div className="flex flex-col gap-6 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <p className="text-xs font-semibold uppercase tracking-wide text-teal">Interview feedback</p>
          <h1 className="mt-1 font-display text-2xl font-semibold text-ink">Your interview report</h1>
          <p className="mt-1 text-sm text-ink-soft">
            {jobDescription} · {formatDate(generatedAt)}
          </p>
        </div>
        <div className="flex items-center gap-4">
          <ScoreDial score={score} tone="teal" size={92} />
          {report.resultLabel && <StatusPill tone={RESULT_TONE[report.resultLabel] || "teal"}>{report.resultLabel}</StatusPill>}
        </div>
      </div>

      <div className="mt-8 flex flex-col gap-6">
        <ReportSection title="Overall impression">
          <p className="text-sm leading-relaxed text-ink-soft">{report.overallSummary}</p>
        </ReportSection>

        <ReportSection title="Skill breakdown">
          <CompetencyBars items={report.competencyScores} />
        </ReportSection>

        <ReportSection title="Strengths">
          <BulletList items={report.strengths} emptyText="No specific strengths were highlighted this time." />
        </ReportSection>

        <ReportSection title="Areas to grow">
          <BulletList items={report.areasToImprove} tone="amber" emptyText="No specific growth areas were highlighted this time." />
        </ReportSection>

        <ReportSection title="Tips for next time">
          <BulletList items={report.tips} emptyText="Keep doing what you're doing." />
        </ReportSection>
      </div>

      <div className="mt-8 flex flex-col items-start gap-2 border-t border-line pt-6 sm:flex-row sm:items-center sm:justify-between">
        <p className="text-xs text-ink-faint">Generated by AI from your interview transcript — use it alongside your own judgment.</p>
        <Button onClick={onDownloadPdf} loading={downloading}>
          <FiDownload size={16} /> Download PDF
        </Button>
      </div>
    </div>
  );
};

export default CandidateReportView;
