import { FiDownload, FiRefreshCw } from "react-icons/fi";
import ScoreDial from "../ui/ScoreDial";
import StatusPill from "../ui/StatusPill";
import Button from "../ui/Button";
import ReportSection from "./ReportSection";
import { CompetencyBars, BulletList } from "./ReportBits";
import { formatDate } from "../../utils/formatters";

const RECOMMENDATION_TONE = { Hire: "green", Maybe: "amber", Reject: "red" };

const InterviewerReportView = ({ data, onDownloadPdf, downloading, onRegenerate, regenerating }) => {
  const { candidateName, jobDescription, generatedAt, score, recommendation, llmModel, report } = data;

  return (
    <div className="rounded-2xl border border-line bg-white p-6 sm:p-8">
      <div className="flex flex-col gap-6 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <p className="text-xs font-semibold uppercase tracking-wide text-teal">Interview evaluation</p>
          <h1 className="mt-1 font-display text-2xl font-semibold text-ink">{candidateName}</h1>
          <p className="mt-1 text-sm text-ink-soft">
            {jobDescription} · {formatDate(generatedAt)}
          </p>
        </div>
        <div className="flex items-center gap-4">
          <ScoreDial score={score} tone={RECOMMENDATION_TONE[recommendation] || "teal"} size={92} />
          {recommendation && <StatusPill tone={RECOMMENDATION_TONE[recommendation] || "teal"}>{recommendation}</StatusPill>}
        </div>
      </div>

      <div className="mt-8 flex flex-col gap-6">
        <ReportSection title="Summary">
          <p className="text-sm leading-relaxed text-ink-soft">{report.overallSummary}</p>
        </ReportSection>

        <ReportSection title="Competency breakdown">
          <CompetencyBars items={report.competencyScores} />
        </ReportSection>

        <ReportSection title="Strengths">
          <BulletList items={report.strengths} />
        </ReportSection>

        <ReportSection title="Concerns">
          <BulletList items={report.concerns} tone="amber" emptyText="No concerns noted." />
        </ReportSection>

        {report.redFlags?.length > 0 && (
          <ReportSection title="Red flags">
            <BulletList items={report.redFlags} tone="red" />
          </ReportSection>
        )}

        <ReportSection title="Communication">
          <p className="text-sm leading-relaxed text-ink-soft">{report.communicationNotes}</p>
        </ReportSection>

        <ReportSection title="Technical / role notes">
          <p className="text-sm leading-relaxed text-ink-soft">{report.technicalNotes}</p>
        </ReportSection>

        <ReportSection title="Resume alignment">
          <p className="text-sm leading-relaxed text-ink-soft">{report.resumeAlignment}</p>
        </ReportSection>

        <ReportSection title="Suggested follow-up questions">
          <BulletList items={report.suggestedFollowUpQuestions} emptyText="None suggested." />
        </ReportSection>
      </div>

      <div className="mt-8 flex flex-col items-start gap-3 border-t border-line pt-6 sm:flex-row sm:items-center sm:justify-between">
        <p className="text-xs text-ink-faint">Generated by {llmModel || "AI"} — verify before making a hiring decision.</p>
        <div className="flex gap-2">
          <Button variant="secondary" onClick={onRegenerate} loading={regenerating}>
            <FiRefreshCw size={15} /> Regenerate
          </Button>
          <Button onClick={onDownloadPdf} loading={downloading}>
            <FiDownload size={16} /> Download PDF
          </Button>
        </div>
      </div>
    </div>
  );
};

export default InterviewerReportView;
