const {
  newDocument,
  formatDate,
  drawHeader,
  drawSectionTitle,
  drawParagraph,
  drawBulletList,
  drawPill,
  drawScoreCircle,
  drawCompetencyBars,
  ensureSpace,
  finalizeWithFooters,
} = require("./pdf.builder");

/** Collects a PDFDocument's output into a single Buffer. */
const bufferDocument = (doc) =>
  new Promise((resolve, reject) => {
    const chunks = [];
    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);
  });

const resultTone = { "Strong Match": "green", "Potential Match": "amber", "Keep Practicing": "teal" };
const recommendationTone = { Hire: "green", Maybe: "amber", Reject: "red" };

const buildCandidatePdf = async ({ candidateName, jobDescription, generatedAt, score, report }) => {
  const doc = newDocument();
  const bufferPromise = bufferDocument(doc);

  drawHeader(doc, {
    eyebrow: "Interview Feedback",
    title: "Your Interview Report",
    candidateName,
    jobDescription,
    dateStr: formatDate(generatedAt),
  });

  const topY = doc.y;
  const rightColumnX = doc.page.width - 130;
  const leftColumnWidth = rightColumnX - 50 - 30; // leave a gap before the score circle

  if (typeof score === "number") {
    drawScoreCircle(doc, score, { x: rightColumnX, y: topY, radius: 36, tone: "teal" });
  }
  if (report.resultLabel) {
    drawPill(doc, report.resultLabel, { x: rightColumnX - 6, y: topY + 84, tone: resultTone[report.resultLabel] || "teal" });
  }

  doc.fillColor("#14171F").font("Helvetica-Bold").fontSize(11).text("Overall impression", 50, topY, { width: leftColumnWidth });
  doc.moveDown(0.4);
  drawParagraph(doc, report.overallSummary, { width: leftColumnWidth });

  // The right-hand circle+pill block is a fixed height; make sure the
  // next section starts below whichever column (text or circle) is taller.
  doc.y = Math.max(doc.y, topY + 112);

  ensureSpace(doc, 100);
  drawSectionTitle(doc, "Skill breakdown");
  drawCompetencyBars(doc, report.competencyScores);

  drawSectionTitle(doc, "Strengths");
  drawBulletList(doc, report.strengths, { emptyText: "No specific strengths were highlighted this time." });

  drawSectionTitle(doc, "Areas to grow");
  drawBulletList(doc, report.areasToImprove, { emptyText: "No specific growth areas were highlighted this time." });

  drawSectionTitle(doc, "Tips for next time");
  drawBulletList(doc, report.tips, { emptyText: "Keep doing what you're doing!" });

  finalizeWithFooters(doc, "Generated by AI from your interview transcript — always use your own judgment alongside this feedback.");
  doc.end();
  return bufferPromise;
};

const buildInterviewerPdf = async ({ candidateName, jobDescription, generatedAt, score, recommendation, llmModel, report }) => {
  const doc = newDocument();
  const bufferPromise = bufferDocument(doc);

  drawHeader(doc, {
    eyebrow: "Interview Evaluation",
    title: "Candidate Evaluation Report",
    candidateName,
    jobDescription,
    dateStr: formatDate(generatedAt),
  });

  const topY = doc.y;
  const rightColumnX = doc.page.width - 130;
  const leftColumnWidth = rightColumnX - 50 - 30;

  if (typeof score === "number") {
    drawScoreCircle(doc, score, { x: rightColumnX, y: topY, radius: 36, tone: recommendationTone[recommendation] || "teal" });
  }
  if (recommendation) {
    drawPill(doc, recommendation, { x: rightColumnX - 6, y: topY + 84, tone: recommendationTone[recommendation] || "teal" });
  }

  doc.fillColor("#14171F").font("Helvetica-Bold").fontSize(11).text("Summary", 50, topY, { width: leftColumnWidth });
  doc.moveDown(0.4);
  drawParagraph(doc, report.overallSummary, { width: leftColumnWidth });

  doc.y = Math.max(doc.y, topY + 112);

  ensureSpace(doc, 100);
  drawSectionTitle(doc, "Competency breakdown");
  drawCompetencyBars(doc, report.competencyScores);

  drawSectionTitle(doc, "Strengths");
  drawBulletList(doc, report.strengths);

  drawSectionTitle(doc, "Concerns");
  drawBulletList(doc, report.concerns, { emptyText: "No concerns noted." });

  if (report.redFlags && report.redFlags.length > 0) {
    drawSectionTitle(doc, "Red flags");
    drawBulletList(doc, report.redFlags);
  }

  drawSectionTitle(doc, "Communication");
  drawParagraph(doc, report.communicationNotes);

  drawSectionTitle(doc, "Technical / role notes");
  drawParagraph(doc, report.technicalNotes);

  drawSectionTitle(doc, "Resume alignment");
  drawParagraph(doc, report.resumeAlignment);

  drawSectionTitle(doc, "Suggested follow-up questions");
  drawBulletList(doc, report.suggestedFollowUpQuestions, { emptyText: "None suggested." });

  finalizeWithFooters(doc, `Generated by AI (${llmModel || "unknown model"}) from the interview transcript — verify before making a hiring decision.`);
  doc.end();
  return bufferPromise;
};

module.exports = { buildCandidatePdf, buildInterviewerPdf };
